//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library2ISP11_17_ZeyArt_DanArt.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBook
    {
        public int ID { get; set; }
        public string NameBook { get; set; }
        public string NamePublishing { get; set; }
        public int YearOfPublishing { get; set; }
        public string NameGenre { get; set; }
        public string Nickname { get; set; }
        public int NumberOfPages { get; set; }
        public int Cost { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public byte[] Preview { get; set; }
    }
}
